# Generated by Django 4.0.6 on 2024-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftmf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
